services:
  toolinter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toolinter
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env.local
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.toolinter-secure.rule=Host(`toolinter.net`) || Host(`www.toolinter.net`) || Host(`toolinter-168-144-37-19.sslip.io`)
      - traefik.http.routers.toolinter-secure.entrypoints=websecure
      - traefik.http.routers.toolinter-secure.middlewares=toolinter-compress
      - traefik.http.routers.toolinter-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.toolinter-http.rule=Host(`toolinter.net`) || Host(`www.toolinter.net`) || Host(`toolinter-168-144-37-19.sslip.io`)
      - traefik.http.routers.toolinter-http.entrypoints=web
      - traefik.http.routers.toolinter-http.middlewares=toolinter-redirect
      - traefik.http.middlewares.toolinter-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.toolinter-compress.compress=true
      - traefik.http.services.toolinter.loadbalancer.server.port=3000

networks:
  dokploy-network:
    external: true
